### ISSUE TITLE
Support writing functions/threads in lume.serialize

### ISSUE THREAD

**Issue by technomancy** [rxi/lume#15]
Right now in `lume.serialize` it signals an error if you give it a value that cannot be serialized. Usually this is the right choice, but there are times when you are debugging and want to use it to spit out some tables and you don't necessarily need it to be deserializable.

I would suggest that `lume.serialize` take an additional `unreadable_ok` flag which changes the behavior to simply emitting unserializable values using `tostring` instead of erroring out.

I have the code for this if you decide it's a good idea.

**Comment by rxi** [comment]
I'm still not keen on adding this to the library for the same reasons as before (#9).

Additionally the output created by `lume.serialize` isn't particularly nice in the sense of human readability and isn't really meant for the sake of debug-output. I feel an entirely different function which would format the output in a way similar to how python's `print` does would make more sense, such a function would probably be outside the scope of lume, though.

**Comment by technomancy** [comment]
Oops; I totally forgot I had already asked about this. Sorry; must be losing my mind.
