### ISSUE TITLE
setTimeout() and setInterval()

### ISSUE THREAD

**Issue by wuppious** [rxi/lume#24]
Hi! Would it be possible to implement `setTimeout()` and `setInterval()` functions à la [Javascript](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout), along with their respective clearing functions? They would be very useful in many cases.

I am not very good with lua myself, so I don't know how to implement these. I do hope that these functions fit the scope of this library though!

**Comment by rxi** [comment]
The implementation of `setTimeout()` and `setInterval()` would require lume to maintain its own internal event loop which would need to be updated manually by the user. Unfortunately this is outside the scope of the project.

Fortunately there are other libraries — [tick](https://github.com/rxi/tick) and [cron](https://github.com/kikito/cron.lua) to name two — which provide this functionality.

**Comment by wuppious** [comment]
Alright, thanks for your response and and for pointing me to those libraries!
