### ISSUE TITLE
lume.reduce with a falsy initial value

### ISSUE THREAD

**Issue by crockeo** [rxi/lume#32]
Presently, if you provide `lume.reduce` a falsy value for the initial accumulator, the function will act as though nothing has been provided. It looks like this is because on lume.lua:290, there's an implicit falsy check, rather than an explicit nil check. For reference: https://github.com/rxi/lume/blob/master/lume.lua#L290.

This could be solved with the following:

```lua
local started = (first ~= nil) and true or false
```

I'm not so familiar with Lua, so this may add in unexpected behavior, but I thought I'd report it all the same.

EDIT: I'm more than happy to make the change if you want me to, but it seems small enough that it would add a bunch of overhead for me to fork + PR + review + merge.

**Comment by rxi** [comment]
Good catch; thanks!
