### ISSUE TITLE
Just some food for thought... math.round

### ISSUE THREAD

**Issue by aubergine10** [rxi/lume#4]
Been using this in my scripts, pretty fast. Inspiration for an updated lume.round?

```
math.round = function(x)
    return x + 0.5 - (x + 0.5) % 1;
end
```

**Comment by rxi** [comment]
I ran some benchmarks and it looks like you're right: on non-JIT this method does seem to offer a noticeable performance boost.

Unfortunately it doesn't provide the same results as the current implementation of `lume.round()`, which intentionally always rounds away-from-zero on an `xxx.5` value (hence the sign check and use of `ceil()`).

That being said the floor case of the function could be replaced with your method, though ideally a solution would be found where the function would perform the same for values both below and above zero.

Thanks for the suggestion! Performance improvements and suggestions for such are always welcome.

**Comment by aubergine10** [comment]
Yup, would certainly be nice if similar approach could be found that rounds away from 0 :)
