### ISSUE TITLE
luacheck?

### ISSUE THREAD

**Issue by technomancy** [rxi/lume#7]
Would you be interested in a patch to let Lume check out clean under luacheck? It's mostly just changing unused loop variables to `_` and renaming a few shadowing variables.

**Comment by rxi** [comment]
Sorry for the slow response!

I'm not very familiar with luacheck. If it's just the changes you described I see no harm in that if it makes the project's code easier to check for other potential issues using luacheck. Unfortunately I might be hesitant to accept such changes if it goes against the project's current coding style too much or makes many changes with seemingly no benefit (other than to cease luacheck's warnings). It may also be counter productive when I make changes to the project, as I do not use luacheck myself I may inadvertently cause it to emit more warnings with each change I make!

That being said it may not be an issue, this likely depends on how pedantic luacheck's warnings are. In some cases of static analyzers/compilers emitting heavy warnings (eg. `-Weverything` on clang) "fixing" many of the warnings would end up making the code less legible with few, if any, actual benefits.

**Comment by technomancy** [comment]
No problem. I think the changes are pretty tame, but you can judge for yourself; just submitted the PR.

**Comment by rxi** [comment]
Merged your pull request #8 which resolves this so closing this issue.
